### ISSUE TITLE
ヘンテコミッションを強化

### ISSUE THREAD

**Issue by monman53** [wakwakcreate/drinkbar#3]
* [x] ランダムに選択してメッセージを送る
* [x] ヘンテコミッションにレベルを導入する

**Comment by wakwakcreaters** [comment]
ジャスミンティだけに課されるへんてこミッションの難易度を2段階にわけ、ゲーム難易度の選択を最初にできるようにする。
「やさしい」と「むずかしい」
CSVファイルを2種類用意し、「やさしい」を選択したらeasymisson.csvからランダムに出題、「むずかしい」を選択したらhardmission.csvからランダムに出題

**Comment by wakwakcreaters** [comment]
最後にミッションの表示

**Comment by monman53** [comment]
いずれも完了したため close します。
