### ISSUE TITLE
オレンジジュースがジャスミンティは「いない」を選択すると動かないことがある

### ISSUE THREAD

**Issue by wakwakcreaters** [wakwakcreate/drinkbar#7]
オレンジジュースがジャスミンティは「いない」を選択すると動かないことがある、
これはもしかしたら勝敗パターンが登録されていないことがあるからなのか？
あとで詳しく見てみる

**Comment by monman53** [comment]
登録されてない場合は default で引き分けになるようにしてるはずだから、普通にバグの可能性が高い。

**Comment by monman53** [comment]
@wakwakcreaters 止まった後ってゲーム再開できる？

**Comment by wakwakcreaters** [comment]
「いない」を押しても反応なくて、他の選択肢を押すとゲームが進む

**Comment by monman53** [comment]
https://github.com/wakwakcreate/drinkbar/commit/36aa38a1fb1e41543412d9dbc17c83ad8dd68047 にて修正したため close します。
